apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
  name: cluster-identity
  namespace: default
spec:
  allowedNamespaces: {}
  clientID: "${AZURE_CLIENT_ID}"
  clientSecret:
    name: cluster-identity-secret
    namespace: default
  tenantID: "${AZURE_TENANT_ID}"
  type: ServicePrincipal
