---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.10.0/16
  topology:
    class: ${CLUSTER_CLASS_NAME}
    version: ${KUBERNETES_VERSION}
    variables:
    - name: clusterLocation
      value: northeurope
    workers:
      machinePools:
      - class: default-system
        name: mp-0
        replicas: 3
      - class: default-worker
        name: mp-1
        replicas: 3
