apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: ${CLUSTER_CLASS_NAME}
  namespace: default
spec:
  controlPlane:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: AzureManagedControlPlaneTemplate
      name: ${CLUSTER_NAME}-control-plane
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: AzureManagedClusterTemplate
      name: ${CLUSTER_NAME}
  variables:
  - name: clusterLocation
    required: true
    schema:
      openAPIV3Schema:
        type: string
        description: Azure location where the cluster is provisioned
        default: southcentralus
  - name: machinePoolSku
    required: true
    schema:
      openAPIV3Schema:
        type: string
        description: Machine Pool SKU
        default: Standard_D2s_v3
  patches:
    - name: clusterLocation
      definitions:
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: AzureManagedControlPlaneTemplate
            matchResources:
              controlPlane: true
          jsonPatches:
          - op: add
            path: /spec/template/spec/location
            valueFrom:
              variable: clusterLocation
    - name: machinePoolSku
      definitions:
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: AzureManagedMachinePoolTemplate
            matchResources:
              machinePoolClass:
                names:
                - default-worker
                - default-system
          jsonPatches:
          - op: add
            path: /spec/template/spec/sku
            valueFrom:
              variable: machinePoolSku
  workers:
    machinePools:
    - class: default-system
      template:
        bootstrap:
          ref:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
            kind: RKE2ConfigTemplate
            name: ${CLUSTER_NAME}-pool0
        infrastructure:
          ref:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: AzureManagedMachinePoolTemplate
            name: ${CLUSTER_NAME}-pool0
    - class: default-worker
      template:
        bootstrap:
          ref:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
            kind: RKE2ConfigTemplate
            name: ${CLUSTER_NAME}-pool1
        infrastructure:
          ref:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: AzureManagedMachinePoolTemplate
            name: ${CLUSTER_NAME}-pool1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedControlPlaneTemplate
metadata:
  name: ${CLUSTER_NAME}-control-plane
  namespace: default
spec:
  template:
    spec:
      identityRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureClusterIdentity
        name: cluster-identity
      # location: will be set by the patch
      resourceGroupName: "${CLUSTER_NAME}"
      subscriptionID: ${AZURE_SUBSCRIPTION_ID}
      version: ${KUBERNETES_VERSION}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedClusterTemplate
metadata:
  name: ${CLUSTER_NAME}
  namespace: default
spec:
  template:
    spec: {}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePoolTemplate
metadata:
  name: ${CLUSTER_NAME}-pool0
  namespace: default
spec:
  template:
    spec:
      mode: System
      name: pool0
      # sku: will be set by patch
      #sku: Standard_D2s_v3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePoolTemplate
metadata:
  name: ${CLUSTER_NAME}-pool1
  namespace: default
spec:
  template:
    spec:
      mode: User
      name: pool1
      # sku: will be set by patch
      #sku: Standard_D2s_v3
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: RKE2ConfigTemplate
metadata:
  name: ${CLUSTER_NAME}-pool0
  namespace: default
spec:
  template:
    spec: {}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: RKE2ConfigTemplate
metadata:
  name: ${CLUSTER_NAME}-pool1
  namespace: default
spec:
  template:
    spec: {}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
  name: cluster-identity
  namespace: default
spec:
  allowedNamespaces: {}
  clientID: ${AZURE_CLIENT_ID}
  clientSecret:
    name: cluster-identity-secret
    namespace: default
  tenantID: ${AZURE_TENANT_ID}
  type: ServicePrincipal
