apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: "${CLUSTER_NAME}"
  namespace: default
  labels:
    cluster-api.cattle.io/rancher-auto-import: "true"
spec:
  clusterNetwork:
    services:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedControlPlane
    name: "${CLUSTER_NAME}"
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedCluster
    name: "${CLUSTER_NAME}"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedControlPlane
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: "${CLUSTER_NAME}"
  namespace: default
spec:
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureClusterIdentity
    name: cluster-identity
  location: ${AZURE_LOCATION}
  resourceGroupName: "${CLUSTER_NAME}"
  nodeResourceGroupName: "${CLUSTER_NAME}-nodes"
  sshPublicKey: ""
  subscriptionID: "${AZURE_SUBSCRIPTION_ID}"
  version: "${KUBERNETES_VERSION}"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedCluster
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: "${CLUSTER_NAME}"
  namespace: default
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: "${CLUSTER_NAME}-pool0"
  namespace: default
spec:
  clusterName: "${CLUSTER_NAME}"
  replicas: ${CONTROL_PLANE_MACHINE_COUNT}
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: "${CLUSTER_NAME}"
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: "${CLUSTER_NAME}-pool0"
      version: "${KUBERNETES_VERSION}"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: "${CLUSTER_NAME}-pool0"
  namespace: default
spec:
  mode: System
  name: pool0
  sku: "${AZURE_INSTANCE}"
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: "${CLUSTER_NAME}-pool1"
  namespace: default
spec:
  clusterName: "${CLUSTER_NAME}"
  replicas: ${WORKER_MACHINE_COUNT}
  template:
    metadata: {}
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: "${CLUSTER_NAME}"
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: "${CLUSTER_NAME}-pool1"
      version: "${KUBERNETES_VERSION}"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: "${CLUSTER_NAME}-pool1"
  namespace: default
spec:
  mode: User
  name: pool1
  sku: "${AZURE_INSTANCE}"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
  name: cluster-identity
  namespace: default
spec:
  allowedNamespaces: {}
  clientID: "${AZURE_CLIENT_ID}"
  clientSecret:
    name: cluster-identity-secret
    namespace: default
  tenantID: "${AZURE_TENANT_ID}"
  type: ServicePrincipal
---
apiVersion: v1
stringData:
  clientSecret: "${AZURE_CLIENT_SECRET}"
kind: Secret
metadata:
  name: cluster-identity-secret
  namespace: default
type: Opaque
