---
apiVersion: v1
kind: Namespace
metadata:
  name: capd-system
---
apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: InfrastructureProvider
metadata:
  name: docker
  namespace: capd-system
spec:
  secretName: capi-env-variables
  secretNamespace: capi-system
